import { db, releaseCyclesTable, winesTable } from "@workspace/db";

async function seed() {
  console.log("Seeding release cycle…");

  const [cycle] = await db
    .insert(releaseCyclesTable)
    .values({
      program_id: "vintages-may-2026",
      program_label: "May 2026 Vintages Release",
      program_type: "vintages",
      release_date: "2026-05-23",
      closing_date: "2026-06-05",
      wine_count: 14,
    })
    .returning();

  console.log(`Created release cycle id=${cycle.id}`);

  console.log("Seeding wines…");

  await db.insert(winesTable).values([
    {
      release_cycle_id: cycle.id,
      wine_name: "Château Léoville Barton",
      producer: "Barton & Guestier",
      lcbo_number: "18643",
      region: "Bordeaux",
      region_category: "Red Wine",
      vintage: "2019",
      score: "94",
      score_source: "Wine Spectator",
      price: "149.95",
      qty_available: 180,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/chateau-leoville-barton-2019-18643",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Penfolds Grange",
      producer: "Penfolds",
      lcbo_number: "22841",
      region: "South Australia",
      region_category: "Red Wine",
      vintage: "2018",
      score: "98",
      score_source: "James Suckling",
      price: "1050.00",
      qty_available: 36,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/penfolds-grange-2018-22841",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Chablis Grand Cru Les Clos",
      producer: "Domaine Raveneau",
      lcbo_number: "39847",
      region: "Chablis",
      region_category: "White Wine",
      vintage: "2021",
      score: "96",
      score_source: "Vinous",
      price: "229.95",
      qty_available: 72,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/chablis-grand-cru-les-clos-2021-39847",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Barolo Cannubi Boschis",
      producer: "Sandrone",
      lcbo_number: "45291",
      region: "Piedmont",
      region_category: "Red Wine",
      vintage: "2019",
      score: "97",
      score_source: "Wine Advocate",
      price: "310.00",
      qty_available: 60,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/barolo-cannubi-boschis-2019-45291",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Caymus Special Selection",
      producer: "Caymus Vineyards",
      lcbo_number: "33127",
      region: "Napa Valley",
      region_category: "Red Wine",
      vintage: "2020",
      score: "95",
      score_source: "Wine Enthusiast",
      price: "279.95",
      qty_available: 120,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/caymus-special-selection-2020-33127",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Vega Sicilia Único",
      producer: "Vega Sicilia",
      lcbo_number: "59284",
      region: "Ribera del Duero",
      region_category: "Red Wine",
      vintage: "2017",
      score: "98",
      score_source: "Wine Spectator",
      price: "585.00",
      qty_available: 48,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/vega-sicilia-unico-2017-59284",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Côte-Rôtie La Turque",
      producer: "E. Guigal",
      lcbo_number: "60471",
      region: "Rhône",
      region_category: "Red Wine",
      vintage: "2019",
      score: "99",
      score_source: "Wine Advocate",
      price: "495.00",
      qty_available: 42,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/cote-rotie-la-turque-2019-60471",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Gevrey-Chambertin Clos St-Jacques",
      producer: "Domaine Rousseau",
      lcbo_number: "71038",
      region: "Burgundy",
      region_category: "Red Wine",
      vintage: "2020",
      score: "96",
      score_source: "Burghound",
      price: "425.00",
      qty_available: 54,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/gevrey-chambertin-clos-st-jacques-2020-71038",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Meursault Perrières",
      producer: "Domaine Leflaive",
      lcbo_number: "82356",
      region: "Burgundy",
      region_category: "White Wine",
      vintage: "2021",
      score: "95",
      score_source: "Vinous",
      price: "315.00",
      qty_available: 66,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/meursault-perrieres-2021-82356",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Sassicaia",
      producer: "Tenuta San Guido",
      lcbo_number: "93714",
      region: "Tuscany",
      region_category: "Red Wine",
      vintage: "2020",
      score: "97",
      score_source: "James Suckling",
      price: "395.00",
      qty_available: 90,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/sassicaia-2020-93714",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Hermitage Blanc",
      producer: "M. Chapoutier",
      lcbo_number: "10492",
      region: "Rhône",
      region_category: "White Wine",
      vintage: "2020",
      score: "96",
      score_source: "Wine Advocate",
      price: "175.00",
      qty_available: 84,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/hermitage-blanc-2020-10492",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Château Pichon Baron",
      producer: "Château Pichon Baron",
      lcbo_number: "14883",
      region: "Bordeaux",
      region_category: "Red Wine",
      vintage: "2019",
      score: "95",
      score_source: "Wine Spectator",
      price: "199.95",
      qty_available: 144,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/chateau-pichon-baron-2019-14883",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Brunello di Montalcino",
      producer: "Biondi-Santi",
      lcbo_number: "27465",
      region: "Tuscany",
      region_category: "Red Wine",
      vintage: "2018",
      score: "97",
      score_source: "Wine Advocate",
      price: "445.00",
      qty_available: 48,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/brunello-di-montalcino-2018-27465",
      sold_out: false,
    },
    {
      release_cycle_id: cycle.id,
      wine_name: "Opus One",
      producer: "Opus One Winery",
      lcbo_number: "35928",
      region: "Napa Valley",
      region_category: "Red Wine",
      vintage: "2020",
      score: "96",
      score_source: "James Suckling",
      price: "519.95",
      qty_available: 72,
      closing_date: "2026-06-05",
      buy_url: "https://www.lcbo.com/en/opus-one-2020-35928",
      sold_out: false,
    },
  ]);

  console.log("✓ Seeded 14 wines into Supabase");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
